// src/App.tsx
import { useState, useEffect, useMemo } from 'react'
import humanizeDuration from 'humanize-duration'

import Container from 'react-bootstrap/Container';
import ListGroup from 'react-bootstrap/ListGroup';

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCodeBranch, faBarcode, faClock, faWifi, faHourglass } from "@fortawesome/free-solid-svg-icons";

import { loadInfo } from './services/DataService';
import Info from './services/types/Info';
import Data from './components/Data';

function App() {
  const [info, setInfo] = useState<Info | null>()

  useEffect(() => {
    async function loadData() {
      const data = await loadInfo()
      console.log('🐓', data)
      setInfo(data)
    }

    const interval = setInterval(async () => {
      await loadData()
      console.log('Logs every minute', info)
    }, 30 * 1000)

    loadData()

    return () => clearInterval(interval)
  }, [])

  const formattedTime = useMemo(() => {
    const time = info?.system.time

    if (time === undefined) {
      return
    }

    const now = new Date(time * 1000)
    return now.toLocaleString()
  }, [info?.system.time])

  const formattedWifiQuality = useMemo(() => {
    const wifiQuality = info?.network.wifiQuality

    if (wifiQuality === undefined) {
      return
    }

    return `${wifiQuality}%`
  }, [info?.network.wifiQuality])

  const formattedUptime = useMemo(() => {
    const uptime = info?.system.uptime

    if (uptime === undefined) {
      return
    }

    const options = {
      units: ['y', 'mo', 'w', 'd', 'h', 'm'],
      round: true
    }

    return humanizeDuration(uptime * 1000, options)
  }, [info?.system.uptime])

  return (
    <Container className="p-3">
      <h1 className='header'>BedRoom Clock ⏰</h1>

      <h2>Device Info</h2>
      <ListGroup>
        <ListGroup.Item><Data icon={faCodeBranch} value={info?.version} /></ListGroup.Item>
        <ListGroup.Item><Data icon={faBarcode} value={info?.system?.deviceId} /></ListGroup.Item>
        <ListGroup.Item><Data icon={faClock} value={formattedTime} /></ListGroup.Item>
        <ListGroup.Item><Data icon={faWifi} value={formattedWifiQuality} /></ListGroup.Item>
        <ListGroup.Item><Data icon={faHourglass} value={formattedUptime} /></ListGroup.Item>
      </ListGroup>
    </Container>
  )
}

export default App

// src/App.vue
<template>
  <div class="container">
    <h1 class="mb-3">Bedroom Clock</h1>

    <section id="device-info" class="mb-3">
      <h2>Device Info</h2>

      <div>version: <span class="value">{{ version }}</span></div>
      <div>device ID: <strong class="value">{{ deviceId }}</strong></div>

      <div>
        wifi signal:
        <span class="value">{{ wifiQuality }}</span>
      </div>
      <div>time: <span class="value">n.a.</span></div>
      <div>
        uptime:
        <span class="value">{{ uptime }}</span>
      </div>
    </section>
  </div>
</template>

<script>
import humanizeDuration from 'humanize-duration'
//import HelloWorld from './components/HelloWorld.vue'

export default {
  name: 'App',
  components: {
    //HelloWorld
  },
  data() {
    return {
      version: undefined,
      deviceId: undefined,
      wifiQuality: undefined,
      uptime: undefined,
      timer: undefined,
    }
  },
  methods: {
    async loadData() {
      const resp = await fetch('/api/info')
      const data = await resp.json()
      const { system, network } = data

      this.version = data.version
      this.deviceId = system.deviceId
      this.wifiQuality = network.wifiQuality
      this.uptime = humanizeDuration(system.uptime * 1000)
    }
  },
  beforeMount() {
    this.timer = setInterval(async () => { await this.loadData() }, 30000)
  },
  beforeUnmount() {
    clearInterval(this.timer);
  }
}
</script>

<style>
</style>
